### ISSUE TITLE
How to keep the login session active ?

### ISSUE THREAD

**Issue by psychon7** [cmayoracurzio/streamlit_firebase_auth#1]
Hi, thanks for putting out this awesome repo! I wish to understand how to keep the user logged in even if they refresh the page? Can we save the user-id in session state or use cookies ?

**Comment by cmayoracurzio** [comment]
Hi there @psychon7!

Thanks for asking, glad you enjoyed the repo. Unfortunately Streamlit does not support persisting sessions after a browser refresh, so that is not implemented here.
